os: linux
dist: xenial
language: r
r: 3.6.2
cache:
  packages: yes
  directories:
  - $TRAVIS_BUILD_DIR/index_cache
  - $TRAVIS_BUILD_DIR/test_packages_cache
  - $TRAVIS_BUILD_DIR/inference_interractions
  - $TRAVIS_BUILD_DIR/gllvm

before_install:
  - sudo apt-get update
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags
  - sudo apt-get install libgsl0-dev

before_script:
- chmod +x ./_build.sh

script:
- ./_build.sh

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _site
  on:
    branch: master